- modules/common.nix
Enable the recommended nginx SSL config from https://ssl-config.mozilla.org/#server=nginx&config=intermediate as well as some optimisations and useful proxy headers
See https://github.com/NixOS/nixpkgs/blob/6300cde54545835c4948f2b7bee376a8c246b26f/nixos/modules/services/web-servers/nginx/default.nix#L115-L168
https://github.com/NixOS/nixpkgs/blob/6300cde54545835c4948f2b7bee376a8c246b26f/nixos/modules/services/web-servers/nginx/default.nix#L59-L66
> feat: enable recommended nginx settings

- flake.nix
This is required to allow TCP connections to demo workloads until we have a better solution (dedicated IP/FQDN)
> feat: do not force HTTPS on Benefice

- flake.nix
Reverts profianinc/staging#26
`nginx` only listens on 80 and 443, so this has nothing to do with the workloads
> revert: "feat: do not force HTTPS on Benefice"

- flake.nix
- hosts/sgx.equinix.demo.enarx.dev/default.nix
- modules/default.nix
- modules/sgx.nix
```
$ ssh sgx.equinix.demo.enarx.dev sudo enarx platform info           
Enarx version 0.6.0
System Info: Linux 5.18.0-rc3-next-20220422 #1-NixOS SMP PREEMPT_DYNAMIC Thu Jul 7 06:12:49 UTC 2022 x86_64
✔ Backend: sgx
✔ Driver: /dev/sgx_enclave
✔ AESM Daemon Socket: /var/run/aesmd/aesm.socket
✔ CPU: Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz | GenuineIntel
✔  SGX Support
✔   Version 1
✔   Version 2
✔   FLC Support
✔   Max Size (32-bit): 2 GiB
✔   Max Size (64-bit): 64 PiB
✔   MiscSelect: EXINFO
✔   Features: DEBUG | MODE64BIT | PROVISIONING_KEY | EINIT_KEY | KSS
✔   Xfrm: X87 | SSE | AVX | YMM | OPMASK | ZMM_HI256 | HI16_ZMM | MPK
✔   EPC Size: 7 GiB
✗ Backend: sev
✗ Driver: /dev/sev
✔  SEV-SNP is enabled in host kernel
✗  /dev/sev is readable by user
✗  /dev/sev is writable by user
✔ Driver: …
```
> feat(sgx.equinix.demo): enable SGX

- hosts/sgx.equinix.demo.enarx.dev/default.nix
- modules/sgx.nix
Use upstream `aesmd` module to reduce the amount of code we need to maintain, benefit from updates and pretty solid, reviewed, config https://github.com/NixOS/nixpkgs/blob/71d7a4c037dc4f3e98d5c4a81b941933cf5bf675/nixos/modules/services/security/aesmd.nix#L114-L233
> feat(sgx.equinix.demo): use upstream `aesmd`

- deploy/default.nix
- flake.lock
- flake.nix
- nixosConfigurations/default.nix
- overlays/default.nix
- overlays/service.nix
- overlays/tooling.nix
The top-level `flake.nix` grew quite big and became difficult to
maintain. As the functionality is mostly stable now, split into separate
components.
> refactor: split flake into multiple components

- flake.nix
- overlays/images.nix
Example usage:
```
$ nix build .#enarx-sgx-install-iso
```
```
├───checks
│   ├───aarch64-darwin
│   │   ├───activate: derivation 'deploy-rs-check-activate'
│   │   └───schema: derivation 'jsonschema-deploy-system'
│   ├───aarch64-linux
│   │   ├───activate: derivation 'deploy-rs-check-activate'
│   │   └───schema: derivation 'jsonschema-deploy-system'
│   ├───i686-linux
│   │   ├───activate: derivation 'deploy-rs-check-activate'
│   │   └───schema: derivation 'jsonschema-deploy-system'
│   ├───x86_64-darwin
│   │   ├───activate: derivation 'deploy-rs-check-activate'
│   │   └───schema: derivation 'jsonschema-deploy-system'
│   └───x86_64-linux
│       ├───activate: derivation 'deploy-rs-check-activate'
│       └───schema: derivation 'jsonschema-deploy-system'
├───deploy: unknown …
```
> feat: add various images

- flake.lock
- flake.nix
Temporarily, until https://github.com/enarx/enarx/pull/2107 ends up in a release
> build: switch to enarx fork

- flake.lock
- flake.nix
- overlays/service.nix
Rather than depending on binary artifacts build by github actions, depend on the flakes directly
> build: depend on flakes directly

- .github/workflows/deploy.yml
- flake.nix
- nixosConfigurations/services/benefice.nix
- nixosConfigurations/services/drawbridge.nix
- nixosConfigurations/services/steward.nix
- nixosModules/ci.nix
- nixosModules/common.nix
- nixosModules/users.nix
- Add a workaround for #109
- Remove `snp-modprobe` workaround since most recent Enarx kernel is used
- Add private SSH key to CI with access to `deploy` user
> feat: automatic staging deployments

- flake.lock
This updates nixpkgs to include
https://github.com/profianinc/nixpkgs/commit/1def0e60d99216e1457572945bea35c1c592695e
> feat: update nixpkgs for new microcode

- flake.lock
- flake.nix
- nixosConfigurations/services/benefice.nix
See https://benefice.testing.profian.com/ already deployed with the changes
Note that the backend setting has no effect until https://github.com/profianinc/benefice/issues/131 is fixed
> feat: run Enarx via OCI for Benefice instances

- hosts/attest.profian.com/default.nix
- hosts/attest.staging.profian.com/default.nix
- hosts/attest.testing.profian.com/default.nix
- hosts/benefice.testing.profian.com/default.nix
- hosts/nuc-1.infra.profian.com/default.nix
- hosts/sgx.equinix.try.enarx.dev/default.nix
- hosts/snp.equinix.try.enarx.dev/default.nix
- hosts/store.profian.com/default.nix
- hosts/store.staging.profian.com/default.nix
- hosts/store.testing.profian.com/default.nix
- lib/hosts.nix
- nixosConfigurations/infra.nix
- nixosConfigurations/services/benefice.nix
- nixosConfigurations/services/drawbridge.nix
- nixosConfigurations/services/steward.nix
This prepares the repository for having multiple hosts to provide a
single service, by adding a "host" argument to mkHost, which then
decides which host configuration to import.
This allows e.g.:
prod1 = mkSteward x86_64-linux [..] "prod1.attest.profian.com";
prod1 = mkSteward x86_64_linux [..] "prod2.attest.profian.com";
> feat: allow multiple hosts per service

- flake.lock
- flake.nix
Update `benefice` and `nixpkgs` inputs (https://github.com/profianinc/nixpkgs/pull/15)
This PR is blocked on https://github.com/profianinc/benefice/pull/146
This is currently deployed to https://benefice.testing.profian.com
> build: update `benefice`

- flake.lock
- nixosConfigurations/services/steward.nix
The steward nginx configuration has been removed from our nixpkgs.
In order to not break the current set up machines, make sure that we add
the nginx config back here.
> chore: move steward nginx config to here

- flake.lock
- nixosConfigurations/services/benefice.nix
This really should not be necessary, but that's the only solution that
works
This is currently deployed to all systems.
> fix: run Benefice as root

- .github/workflows/build.yml
- deploy/default.nix
- nixosConfigurations/services/steward.nix
This instance has been taken over by the production-{1,2,3,4} instances.
> feat: remove attest.profian.com (the ec2 instance)

- flake.lock
- flake.nix
- nixosConfigurations/services/benefice.nix
- overlays/service.nix
This bumps benefice, and creates a separate production flake input, to keep that separate from staging/testing.
> chore: bump benefice

- nixosConfigurations/services/benefice.nix
> fix: add aesmd and pccs requires on benefice sgx

- .github/workflows/build.yml
- .github/workflows/commisery.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/shell.yml
Also switched Linux-only workflows to https://github.com/nixbuild/nix-quick-install-action, which is faster. `macos-latest` is not supported, however https://github.com/nixbuild/nix-quick-install-action/issues/7
> ci: update actions

- .github/workflows/update.yml
- flake.lock
Automatically run `nix flake update`
See example at https://github.com/rvolosatovs/nixify/pull/22
Note that this is just the first step, most notably these PRs do not trigger `push` and `pull_request` workflows until manually closed and reopened. There are better workarounds https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
I think the right thing to do is to use @enarxbot (or `profianbot`?) for this
Included a `nixpkgs` update commit, because we were quite out-of-date compared to upstream and MacOS actions could not fetch `nixUnstable` from caches anymore
> ci: automate flake update

- flake.lock
- flake.nix
This makes sure that we always use the latest packages from upstream's stable release channel.
We also overlay `linux-firmware` from `unstable` for "bleeding edge" updates
> feat: overlay latest packages from upstream
