profianinc/infrastructure

- flake.lock
- flake.nix
Blocked by https://github.com/profianinc/drawbridge/pull/234
> feat: deploy 0.1.0 Drawbridge version

- .github/workflows/deploy.yml
> ci: disable deployment

- flake.lock
- flake.nix
- hosts/sgx.equinix.demo.enarx.dev/default.nix
- hosts/snp.equinix.demo.enarx.dev/default.nix
- modules/benefice.nix
- modules/default.nix
- modules/enarx.nix
Using `enarx` build from `main` until a point release (or RC of it) is out.
cc @platten @haraldh
> feat: add enarx and benefice modules

- nixosConfigurations/default.nix
> feat(store): increase max body size

- flake.lock
- flake.nix
Closes #70 
Signed-off-by: Paul Pietkiewicz <paul@profian.com>
> chore(deps): bump enarx to official 0.6.1 release

- nixosConfigurations/default.nix
Closes #69 
Signed-off-by: Paul Pietkiewicz <paul@profian.com>
> fix(benefice): disable HSTS on benefice

- flake.nix
- overlays/tooling.nix
For example:
```
ssh-for-each sudo nix-collect-garbage -d
```
> feat: add `ssh-for-each` utility

- flake.lock
- flake.nix
https://github.com/profianinc/benefice/issues/81
https://github.com/profianinc/benefice/issues/82
This reverts commit 881618a85de30f5614cf5d9f68e328f07103f3c0.
> revert: "build: update benefice to v0.1.0-rc10"

- modules/users.nix
Signed-off-by: Paul Pietkiewicz <paul@profian.com>
> chore(access): add openssh deploy access for platten

- flake.nix
- overlays/default.nix
- overlays/images.nix
- overlays/tooling/aws.nix
- overlays/tooling/bootstrap.nix
- overlays/tooling/default.nix
```
$ nix build .#enarx-sev-amazon
$ aws-create-ami ./result
```
> build(nix): add AWS AMI tooling

- flake.nix
Signed-off-by: Roman Volosatovs <roman@profian.com>
> fix: remove outdated TODO

- flake.lock
- flake.nix
This already deployed
cc @npmccallum
> build: update benefice to v0.1.0-rc11

- flake.lock
Signed-off-by: Roman Volosatovs <roman@profian.com>
> build(nix): update flake lock

- flake.lock
> build: update flake lock

- flake.lock
- flake.nix
rolling back these commits: https://github.com/profianinc/benefice/compare/v0.1.0-rc13...v0.1.0-rc14
> build: rollback staging Benefice to v0.1.0-rc13

- .github/workflows/build.yml
- .sops.yaml
- deploy/default.nix
- hosts/benefice.testing.profian.com/default.nix
- hosts/benefice.testing.profian.com/oidc-secret
- hosts/sgx.equinix.try.enarx.dev/default.nix
- hosts/snp.equinix.try.enarx.dev/default.nix
- nixosConfigurations/services/benefice.nix
Note that `services.enarx.enable = true` was moved to `mkBenefice` from individual host configs.
> feat(benefice-testing): init instance

- nixosModules/users.nix
> chore(access): add access for puiterwijk

- .sops.yaml
> chore(keys): add age key for puiterwijk

- ca/profian.com/ca.key
- ca/staging.profian.com/ca.key
- ca/testing.profian.com/ca.key
> chore: reencrypt CA keys

- nixosConfigurations/services/benefice.nix
`enarx:0.6.3` image is available locally on boot
> feat(benefice): enable Docker and preload Enarx image

- flake.lock
- flake.nix
- hosts/benefice.testing.profian.com/default.nix
- nixosConfigurations/services/benefice.nix
This is currently deployed to production and testing environments
> feat: run Benefice workloads in TEEs via OCI

- flake.lock
> build: update dependencies

- .sops.yaml
- nixosConfigurations/services/steward.nix
- nixosModules/cloudflared.nix
- nixosModules/default.nix
- secrets/production/cloudflared/steward
This allows setting up cloudflare tunnels for load balanced production clusters without public IP.
At this moment, it only supports pre-configured tunnels.
> feat: add cloudflared module

- nixosModules/service.nix
- secrets/monitoring_api_token
> feat: add datadog agent for monitoring/logs

- hosts/benefice.testing.profian.com/session-key
- hosts/sgx.equinix.try.enarx.dev/session-key
- hosts/snp.equinix.try.enarx.dev/session-key
- nixosModules/benefice.nix
> feat: create session keys for benefice

- nixosConfigurations/services/benefice.nix
- nixosModules/benefice.nix
> feat: set demoFqdn for benefice

- nixosConfigurations/services/benefice.nix
- nixosConfigurations/services/drawbridge.nix
- nixosConfigurations/services/steward.nix
> feat: specify log level for services production environments

- nixosModules/default.nix
- nixosModules/monitoring.nix
- nixosModules/service.nix
> feat: split out monitoring

- nixosConfigurations/infra.nix
- nixosModules/service.nix
- nixosModules/users.nix
> chore: remove platten

- nixosModules/monitoring.nix
> chore(monitoring): fix tag for environment

- flake.lock
> chore: bump to rebased nixpkgs

- nixosConfigurations/services/benefice.nix
- nixosModules/users.nix
> feat(users): add jarkko

- nixosConfigurations/services/benefice.nix
- nixosModules/users.nix
This reverts commit 6838294090c2d9049ef49804a7310d15777f0a42.
> feat(users): remove jarkko

- .sops.yaml
- hosts/snp.aws.try.enarx.dev/oidc-secret
- hosts/snp.aws.try.enarx.dev/session-key
@puiterwijk please set up monitoring credentials and redeploy
> chore: update SNP AWS Benefice credentials

- flake.lock
- flake.nix
> chore: update to Enarx 0.7.0
